development: &default
  adapter: postgresql
  encoding: utf8
  database: todo_list_development
  host: localhost
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

test:
  <<: *default
  database: todo_list_test

production:
  <<: *default
  database: todo_list_production